-- https://projecteuler.net/problem=45
--
-- Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
--
-- Triangle	    	Tn=n(n+1)/2	    	1, 3, 6, 10, 15, ...
-- Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
-- Hexagonal	 	Hn=n(2n−1)	    	1, 6, 15, 28, 45, ...
-- It can be verified that T285 = P165 = H143 = 40755.
-- Find the next triangle number that is also pentagonal and hexagonal.

triangle :: Integer -> Integer
triangle n = quot (n * (n + 1)) 2

pentagonal :: Integer -> Integer
pentagonal n = quot (n * (3 * n - 1)) 2

hexagonal :: Integer -> Integer
hexagonal n = n * (2 * n - 1)

result :: Integer -> Integer -> Integer -> Integer
result t p h
    | tr == pr && pr == hr    = tr
    | tr < pr                 = result (t+1) p h
    | pr < hr                 = result t (p+1) h
    | otherwise               = result t p (h+1)
    where
        tr = triangle t
        pr = pentagonal p
        hr = hexagonal h


main :: IO ()
main = print ("Expected: " ++ show (1533776805 :: Integer) ++ ", actual: " ++ show (result 144 144 144))
