
-- https://projecteuler.net/problem=2
--
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even-valued terms.

mysum :: (Integral n) => n -> [n] -> n
mysum 0 _ = 0
mysum n [] = mysum n [1, 0]
mysum n [_] = mysum n [1, 0]
mysum n (a : (b : xs)) = if a >= n then sum (filter even (b : xs)) else mysum n ((a + b) : a : b : xs)

main = do
    print (mysum 4000000 [])
